default: &default
  adapter: postgresql
  host: 45.55.170.122
  database: postgres
  username: deploy
  password: <%= Rails.application.secrets.pg_pw %>
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  # adapter: sqlite3
  # database: db/development.sqlite3

test:
  <<: *default
  # database: db/test.sqlite3

production:
  <<: *default
