default: &default
  adapter: postgresql
  host: 45.55.170.122
  database: deploy
  username: deploy
  password: <%= Rails.application.secrets.pg_pw %>
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
