development:
  pg_pw: <%= ENV["PG_PW"] %>
  secret_key_base: <%= ENV["KNG_DEV_SECRET"] %>

test:
  secret_key_base: bc43bfa8fefb888b75ab178e1c5174e51e3af91c319e04b3c7c82a4e78dbe1e748a56ba53277e0aff0f64cf38cd4176ae0acd60e85f6480e72ab02e393702452

production:
  pg_pw: <%= ENV["PG_PW"] %>
  secret_key_base: <%= ENV["KNG_PROD_SECRET"] %>
